#!/usr/bin/env ruby

require 'calendarium-romanum/historical'
require 'calendarium-romanum/historical/cli'

# Don't warn about enforcing locales in the CLI.
I18n.config.enforce_available_locales = true

CalendariumRomanum::Historical::CLI.start ARGV
